---
- name: Set up Kubernetes cluster
  hosts: localhost
  vars_files:
    - secrets.yaml  # This file is encrypted with Ansible Vault

  tasks:
    # Log in to Azure CLI using the Service Principal credentials
    - name: Log in to Azure CLI with Service Principal
      ansible.builtin.command:
        cmd: >
          az login --service-principal -u {{ azure.client_id }} -p {{ azure.client_secret }} --tenant {{ azure.tenant_id }}
      become: yes

    # Get the AKS cluster credentials to interact with the cluster
    - name: Get AKS credentials
      ansible.builtin.command:
        cmd: az aks get-credentials --resource-group {{ terraform.resource_group }} --name {{ terraform.cluster_name }} --overwrite-existing
      become: yes

    # Authenticate with Kubelogin for Azure CLI integration
    - name: Authenticate with Kubelogin
      ansible.builtin.command:
        cmd: kubelogin convert-kubeconfig -l azurecli
      become: yes

    # Deploy the Nginx Ingress Controller to the Kubernetes cluster
    - name: Apply Nginx Ingress Controller
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      become: yes

    # Deploy Cert Manager for managing certificates
    - name: Apply Cert Manager
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
      become: yes

    # Apply logging manifests to set up logging in the Kubernetes cluster
    - name: Apply Logging Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/manifests-logging
      become: yes

    # Deploy the Sock-Shop microservices application
    - name: Apply Sock-Shop Microservices Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/complete-demo.yaml
      become: yes

    # Apply monitoring manifests for monitoring the Kubernetes cluster
    - name: Apply Monitoring Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/manifests-monitoring
      become: yes

    # Apply alerting manifests for setting up alerts
    - name: Apply Alerting Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/manifests-alerting
      become: yes

    # Apply network policy manifests for network security
    - name: Apply Network Policy Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/manifests-policy
      become: yes

    # Apply issuer and ingress manifests for certificate management and ingress configuration
    - name: Apply Issuer and Ingress Manifests
      ansible.builtin.command:
        cmd: kubectl apply -f microservices_manifests/ingress.yaml
      become: yes

    # Optional: Uncomment to apply pod autoscaling manifests
    # - name: Apply Pod Autoscaling Manifests
    #   ansible.builtin.command:
    #     cmd: kubectl apply -f microservices_manifests/autoscaling
    #   become: yes

    # Retrieve and display all pods in all namespaces
    - name: Get all pods in all namespaces
      ansible.builtin.command:
        cmd: kubectl get pods --all-namespaces
      register: pods_output
      become: yes

    - name: Display all pods in all namespaces
      ansible.builtin.debug:
        msg: "{{ pods_output.stdout }}"

    # Retrieve and display all ingress resources
    - name: Get all ingress resources
      ansible.builtin.command:
        cmd: kubectl get ingress
      register: ingress_output
      become: yes

    - name: Display all ingress resources
      ansible.builtin.debug:
        msg: "{{ ingress_output.stdout }}"
