# This file contains the Horizontal Pod Autoscaler configuration for the orders service
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: orders

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
