# This file is used to create a Job that imports Grafana dashboards and datasources.

apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-import-dashboards
  namespace: monitoring
  labels:
    app: grafana
    component: import-dashboards
spec:
  template:
    metadata:
      name: grafana-import-dashboards
      labels:
        app: grafana
        component: import-dashboards
    spec:
      initContainers:
      - name: wait-for-endpoints
        image: giantswarm/tiny-tools
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
        args:
          - |
            echo "waiting for endpoints..."
            while true; do
              endpoints=$(curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --header "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc/api/v1/namespaces/monitoring/endpoints/grafana)
              echo "$endpoints" | jq "."
              if [ $(echo "$endpoints" | jq -r ".subsets[].addresses | length") -gt 0 ]; then
                exit 0
              fi
              echo "waiting..."
              sleep 1
            done
      containers:
      - name: grafana-import-dashboards
        image: giantswarm/tiny-tools
        command: ["/bin/sh", "-c"]
        workingDir: /opt/grafana-import-dashboards
        args:
          - |
            for file in *-datasource.json ; do
              if [ -e "$file" ] ; then
                echo "importing $file" &&
                curl --silent --fail --show-error \
                  --request POST http://admin:admin@grafana/api/datasources \
                  --header "Content-Type: application/json" \
                  --header "Accept: application/json" \
                  --data-binary "@$file" ;
                echo "" ;
              fi
            done ;
            for file in *-dashboard.json ; do
              if [ -e "$file" ] ; then
                echo "importing $file" &&
                curl --silent --fail --show-error \
                  --request POST http://admin:admin@grafana/api/dashboards/import \
                  --header "Content-Type: application/json" \
                  --header "Accept: application/json" \
                  --data-binary "@$file" ;
                echo "" ;
              fi
            done ;
        volumeMounts:
        - name: config-volume-1
          mountPath: /opt/grafana-import-dashboards/k8s-pod-resources-dashboard
        - name: config-volume-2
          mountPath: /opt/grafana-import-dashboards/prometheus-datasource
        - name: config-volume-3
          mountPath: /opt/grafana-import-dashboards/prometheus-node-exporter-dashboard
        - name: config-volume-4
          mountPath: /opt/grafana-import-dashboards/prometheus-stats-dashboard
        - name: config-volume-5
          mountPath: /opt/grafana-import-dashboards/sock-shop-analytics-dashboard
        - name: config-volume-6
          mountPath: /opt/grafana-import-dashboards/sock-shop-performance-dashboard
        - name: config-volume-7
          mountPath: /opt/grafana-import-dashboards/sock-shop-resources-dashboard
      restartPolicy: Never
      volumes:
      - name: config-volume-1
        configMap:
          name: grafana-import-dashboards-k8s-pod-resources-dashboard
      - name: config-volume-2
        configMap:
          name: grafana-import-dashboards-prometheus-datasource
      - name: config-volume-3
        configMap:
          name: grafana-import-dashboards-prometheus-node-exporter-dashboard
      - name: config-volume-4
        configMap:
          name: grafana-import-dashboards-prometheus-stats-dashboard
      - name: config-volume-5
        configMap:
          name: grafana-import-dashboards-sock-shop-analytics-dashboard
      - name: config-volume-6
        configMap:
          name: grafana-import-dashboards-sock-shop-performance-dashboard
      - name: config-volume-7
        configMap:
          name: grafana-import-dashboards-sock-shop-resources-dashboard
