# This is the ConfigMap for the AlertManager. It contains the configuration for the AlertManager, including the Slack hook URL, the routing rules, and the receivers. The Slack hook URL is stored in a secret and is injected into the ConfigMap using a script that runs when the ConfigMap is created. The ConfigMap is mounted as a volume in the AlertManager pod, so that the AlertManager can read the configuration from the ConfigMap.

kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
data:
  config.yml: |-
    global:
      slack_api_url: https://hooks.slack.com/services/API_URL_SECRET

    route:
      group_by: [cluster]
      # If an alert isn't caught by a route, send it slack.
      receiver: slack-all
      routes:
        - match:
            severity: slack
          receiver: slack-all


    receivers:
    - name: 'slack-all'
      slack_configs:
      - channel: '#sockshop-ops'
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        api_url: https://hooks.slack.com/services/API_URL_SECRET
  configure_secret.sh: |-
    echo 'Configuring Slack hook url.'
    cp /etc/alertmanager/config.yml /tmp/config.yml
    sed -i -e s,API_URL_SECRET,"$SLACK_HOOK_URL",g /tmp/config.yml
    exec /bin/alertmanager --config.file=/tmp/config.yml

